#!/bin/bash
set -eu

# Check if Homebrew is installed by checking the following locations:
# 1. The `brew` command is available in the PATH
# 2. The HOMEBREW_PREFIX environment variable is set and points to a valid Homebrew installation
# 3. The default Homebrew installation paths for macOS and Linux
if command -v brew >/dev/null 2>&1; then
  HOMEBREW_EXECUTABLE="$(command -v brew)"
elif [[ -n "${HOMEBREW_PREFIX-}" && -f "${HOMEBREW_PREFIX}/bin/brew" ]]; then
  HOMEBREW_EXECUTABLE="${HOMEBREW_PREFIX}/bin/brew"
elif [[ -f /opt/homebrew/bin/brew ]]; then
  HOMEBREW_EXECUTABLE="/opt/homebrew/bin/brew"
elif [[ -f /home/linuxbrew/.linuxbrew/bin/brew ]]; then
  HOMEBREW_EXECUTABLE="/home/linuxbrew/.linuxbrew/bin/brew"
else
  # Intentionally don't expand characters
  # shellcheck disable=SC2016
  printf '%s\n' 'Homebrew was not found. Please set $HOMEBREW_PREFIX or install it using the following command:'
  # Intentionally don't expand characters
  # shellcheck disable=SC2016
  printf '%s\n' '  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  exit 1
fi

BREWFILE_PATH="$(dirname "$0")/Brewfile"
$HOMEBREW_EXECUTABLE bundle install --file="$BREWFILE_PATH" --no-upgrade
